
services:
  mysql:
    image: mysql:8.0.36        # version stable et largement utilisée
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: .
    container_name: bibliotheque-api
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy    # ← C’EST ÇA QUI CHANGE TOUT
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=mydb;User=myuser;Password=rootpass;SslMode=none;
    ports:
      - "5000:5000"
      #- "7275:7275"   # si tu utilises les ports aléatoires de Visual Studio
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:
